{% set name = "nnetsauce" %}
{% set version = "0.31.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Techtonique/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 611f90ec11a7dce0a8c6cb1436da5c5db03152538020bc75dc929b15c44ff8b4
  
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py < 39]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - jax >=0.1.72      # [unix]
    - jaxlib >=0.1.51      # [unix]
    - matplotlib-base
    - numpy >=1.14.0
    - scipy >=0.19.0
    - scikit-learn >=0.18.0
    - pandas >=1.3.5
    - joblib >=0.14.0
    - pyvinecopulib >=0.6.6
    - six >=1.16.0
    - threadpoolctl >=2.0.0
    - tqdm >=4.48.1
    - requests
    - statsmodels
  run:
    - python
    - scipy >=0.19.0
    - scikit-learn >=0.18.0
    - matplotlib-base
    - jax >=0.1.72      # [unix]
    - jaxlib >=0.1.51      # [unix]
    - pandas >=1.3.5
    - joblib >=0.14.0
    - pyvinecopulib >=0.6.6
    - six >=1.16.0
    - threadpoolctl >=2.0.0
    - tqdm >=4.48.1
    - requests
    - statsmodels
    - {{ pin_compatible('numpy') }}

test:
  imports: nnetsauce

about:
  home: https://techtonique.github.io/nnetsauce/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Randomized and quasi-randomized networks for Statistical/Machine Learning
  description: Randomized and quasi-randomized (neural) networks for Statistical/Machine Learning.
  doc_url: https://techtonique.github.io/nnetsauce/
  dev_url: https://github.com/Techtonique/nnetsauce

extra:
  recipe-maintainers:
    - thierrymoudiki
