{% set name = "nnetsauce" %}
{% set version = "0.24.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Techtonique/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f230e683f7ee82c2bc952aa72f674f623dd5e8d72567b2dd0725e0dcb079926a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py < 35]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - matplotlib >=3.7.1
    - numpy >=1.14.0
    - scipy >=0.19.0
    - scikit-learn >=0.18.0
    - pandas >=1.3.5
    - joblib >=0.14.0
    - pyvinecopulib >=0.6.6
    - six >=1.16.0
    - threadpoolctl >=2.0.0
    - tqdm >=4.48.1
    - requests
    - statsmodels
  run:
    - python
    - scipy >=0.19.0
    - scikit-learn >=0.18.0
    - matplotlib >=3.7.1
    - pandas >=1.3.5
    - joblib >=0.14.0
    - pyvinecopulib >=0.6.6
    - six >=1.16.0
    - threadpoolctl >=2.0.0
    - tqdm >=4.48.1
    - requests
    - statsmodels
    - {{ pin_compatible('numpy') }}

test:
  imports: nnetsauce

about:
  home: https://techtonique.github.io/nnetsauce/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Randomized and quasi-randomized networks for Statistical/Machine Learning
  description: Randomized and quasi-randomized (neural) networks for Statistical/Machine Learning.
  doc_url: https://techtonique.github.io/nnetsauce/
  dev_url: https://github.com/Techtonique/nnetsauce

extra:
  recipe-maintainers:
    - thierrymoudiki
